# 当前eureka server的端口为8761
server:
  port: 8761
# 当前eureka server的地址为localhost
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #当前服务不需要到eureka server上注册
    fetch-registry: false